---
- name: Ensure $HOME/.redis exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.redis"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0755"

- name: Create redis configuration.
  ansible.builtin.template:
    src: redis_conf.j2
    dest: "{{ ansible_env.HOME }}/.redis/conf"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0644"

- name: Create redis daemon configuration.
  ansible.builtin.template:
    src: redis_daemon.ini.j2
    dest: "{{ ansible_env.HOME }}/etc/services.d/redis.ini"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0644"

- name: Start redis daemon.
  community.general.supervisorctl:
    name: redis
    state: present
