---

uberspace_yourls__document_root: "/var/www/virtual/{{ ansible_facts.user_id }}/html"
uberspace_yourls__version: "1.8.2"
uberspace_yourls__release_url: "https://github.com/YOURLS/YOURLS/tarball/1.8.2"
uberspace_yourls__database_name: "{{ ansible_facts.user_id }}_yourls"
uberspace_yourls__domain: "{{ ansible_facts.user_id }}.uber.space"
# Change this setting to use a translation file for your language, instead of the default English.
# That translation file (a .mo file) must be installed in the user/language directory.
# See http://yourls.org/translations for more information
uberspace_yourls__language: ""

# Allow multiple short URLs for a same long URL
# Set to true to have only one pair of shortURL/longURL (default YOURLS behavior)
# Set to false to allow multiple short URLs pointing to the same long URL (bit.ly behavior)
uberspace_yourls__unique_urls: true

# Private means the Admin area will be protected with login/pass as defined below.
# Set to false for public usage (eg on a restricted intranet or for test setups)
# Read http://yourls.org/privatepublic for more details if you're unsure
uberspace_yourls__private: true

# A random secret hash used to encrypt cookies. You don't have to remember it, make it long and complicated
# Hint: copy from http://yourls.org/cookie
# !!!! PLEASE NOTE: THIS DEFAULT KEY IS NOT SECURE !!!!
uberspace_yourls__cookiekey: "{{ (ansible_hostname + ansible_user_id) | hash('sha256') }}"

# URL shortening method: either 36 or 62
# 36: generates all lowercase keywords (ie: 13jkm)
# 62: generates mixed case keywords (ie: 13jKm or 13JKm)
# For more information, see https://yourls.org/urlconvert
uberspace_yourls__url_shortening_method: 36

# Read http://yourls.org/userpassword for more information
# This ansible module will auto encrypt plain text passwords with md5,
# which is slightly less secure than YOURLS encryption, but still better than plain text.
uberspace_yourls__users:
  - username: "{{ ansible_facts.user_id }}"
    password: "PleaseChangeMe"

# Debug mode to output some internal information
# Default is false for live site. Enable when coding or before submitting a new issue
uberspace_yourls__debug: false


# Install Pseudonymize Plugin
# By default YOURLS logs every visit on a shortlink with the complete IP address of the visitor.
# This toggles the installation of the plugin. You still have to manually activate it in the Web-UI.
uberspace_yourls__pseudonymize: true

# Additional plugins to install
# This can be a list of dicts of repositories. version parameter is optional (HEAD will be used)
# e.g.
# uberspace_yourls__additional_plugins:
#   - repo: https://github.com/YOURLS/404-if-not-found
#     version: master
#   - repo: https://github.com/adigitalife/yourls-allow-aliases
#     version: master

uberspace_yourls__additional_plugins: []
