---

- name: Update list of domains.
  shell: >
    uberspace web domain
    {{ 'add' if (item.state | default('present')).lower() == 'present' else '' }}
    {{ 'del' if (item.state | default('present')).lower() == 'absent' else '' }}
    $(idn {{ item.domain }})
  when:
    ((item.state | default('present')).lower() == 'present' and item.domain not in ansible_local.users[ansible_user_id].domains) or
    ((item.state | default('present')).lower() == 'absent' and item.domain in ansible_local.users[ansible_user_id].domains)
  loop: "{{ uberspace_domain__domains + ([{'domain': uberspace_domain__domain, 'state': uberspace_domain__state}] if uberspace_domain__domain else []) }}"

- name: Create Document Roots.
  file:
    path: "/var/www/virtual/{{ ansible_user_id }}/{{ item.domain }}"
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: 0775
  when: (item.state | default('present')).lower() == 'present' and ( item.create_docroot | default(true) )
  loop: "{{ uberspace_domain__domains + ([{'domain': uberspace_domain__domain, 'state': uberspace_domain__state}] if uberspace_domain__domain else []) }}"
