---
- name: Execute my_print_defaults.
  ansible.builtin.command:
    cmd: my_print_defaults client
  register: my_defaults_result
  failed_when: my_defaults_result.rc != 0
  changed_when: false
  check_mode: false
  no_log: true

- name: Get MySQL user from my_print_defaults.
  ansible.builtin.set_fact:
    uberspace_mysql_user: "{{ my_defaults_result.stdout | regex_search(regex, '\\1') | first }}"
  vars:
    regex: --user=(.*)
  failed_when: not uberspace_mysql_user
  no_log: true

- name: Get MySQL password from my_print_defaults.
  ansible.builtin.set_fact:
    uberspace_mysql_password: "{{ my_defaults_result.stdout | regex_search(regex, '\\1') | first }}"
  vars:
    regex: --password=(.*)
  failed_when: not uberspace_mysql_password
  no_log: true
