---

- name: uberspace_redis | Ensure $HOME/.redis exists.
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.redis"
    state: directory
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: 0755

- name: uberspace_redis | Create redis configuration.
  ansible.builtin.template:
    src: redis_conf.j2
    dest: "{{ ansible_env.HOME }}/.redis/conf"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: 0644

- name: uberspace_redis | Create redis daemon configuration.
  ansible.builtin.template:
    src: redis_daemon.ini.j2
    dest: "{{ ansible_env.HOME }}/etc/services.d/redis.ini"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: 0644

- name: uberspace_redis | Set redis daemon to desired state..
  community.general.supervisorctl:
    name: redis
    state: "{{ 'present' if uberspace_redis__enable else 'absent' }}"
