---
- name: Restart PHP service.
  ansible.builtin.command: uberspace tools restart php

- name: Rewrite Nextcloud htaccess.
  ansible.builtin.command: php occ maintenance:update:htaccess
  args:
    chdir: "{{ uberspace_nextcloud__document_root }}"
