---

- name: Get MySQL password.
  include_role:
    name: mysql
    tasks_from: get_login

- name: Create database for Wallabag.
  community.mysql.mysql_db:
    name: "{{ uberspace_wallabag__database_name }}"
    login_user: "{{ uberspace_mysql_user }}"
    login_password: "{{ uberspace_mysql_password }}"
    state: present

- name: Clone wallabag into Document Root.
  ansible.builtin.git:
    repo: "{{ uberspace_wallabag__repository }}"
    dest: "{{ uberspace_wallabag__document_root }}"
    version: "{{ uberspace_wallabag__repository_version }}"

- name: Write parameter file.
  ansible.builtin.template:
    src: parameters.yml.j2
    dest: "{{ uberspace_wallabag__document_root }}/app/config/parameters.yml"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0664"
  register: wallabag_parameters
  no_log: True
  notify:
    - Run wallabag install.
    - Clear wallabag cache.

- name: Run composer.
  ansible.builtin.shell:
    cmd: SYMFONY_ENV=prod composer install --no-dev -o --prefer-dist
    chdir: "{{ uberspace_wallabag__document_root }}"

- name: Configure webserver for rewrites.
  template:
    src: htaccess.j2
    dest: "{{ uberspace_wallabag__document_root }}/.htaccess"
    owner: "{{ ansible_facts.user_id }}"
    group: "{{ ansible_facts.user_id }}"
    mode: "0644"
